version: "3.7"
services:
  aria2bot:
    image: jwstar/aria2bot
    network_mode: host
    container_name: aria2bot
    restart: always
    volumes:
      - ./db:/app/db
      - /tmp/downloads:/root/downloads    # 修改为你要挂载的下载路径
    build: .
    environment:
      TZ: Asia/Shanghai